# -*- coding: utf-8 -*-
"""Part a eda.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os; os.chdir("/content")
from common import *
import matplotlib.pyplot as plt

def run_eda(df):
    print("Shape:", df.shape)
    print("\nData types:\n", df.dtypes)

    print("\nMissing values:")
    missing = df.isna().sum()
    print(missing[missing > 0])
    print("Missing %:\n", (missing[missing > 0] / len(df) * 100).round(2))

    print("\nDescriptive statistics:\n",
          df[NUMERIC_COLS + [REG_TARGET]].describe().round(2))

    counts = df[CLASS_TARGET].value_counts()
    print("\nChurn distribution:\n", counts)
    print("Churn rate: %.1f%%" % (100 * (df[CLASS_TARGET] == "Yes").mean()))
    counts.plot(kind="bar", title="Churn Distribution")
    save_fig("churn_distribution.png")

    df[NUMERIC_COLS].hist(bins=25, figsize=(12, 8))
    save_fig("numeric_distributions.png")

    for col in ["ContractType", "AutoPay"]:
        rate = df.groupby(col)[CLASS_TARGET].apply(lambda s: (s == "Yes").mean())
        print("\nChurn rate by %s (%%):\n%s" % (col, (rate * 100).round(1)))
        rate.plot(kind="bar", title="Churn rate by " + col)
        plt.ylabel("Churn rate")
        save_fig("churn_by_%s.png" % col.lower())

    print("\n--- Part A answers ---")
    print("1. Exclude:", ID_COL, "(unique identifier, no predictive meaning).")
    print("2. Future12MRevenueEGP is measured after the current period and is "
          "affected by churn itself -> target leakage.")
    print("3. No: churn is imbalanced (~18%), so predicting 'No' for everyone "
          "gives ~82% accuracy while catching zero churners.")
    print("4. Scale-sensitive: KNN, SVM, Logistic/Linear (regularized), "
          "K-Means, PCA, DBSCAN. Trees/forests are not.")


if __name__ == "__main__":
    run_eda(load_data())