# -*- coding: utf-8 -*-
"""common.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os
import warnings
warnings.filterwarnings("ignore")

import matplotlib
try:
    get_ipython()
except NameError:
    matplotlib.use("Agg")
import matplotlib.pyplot as plt
import pandas as pd

RANDOM_STATE = 42

try:
    _here = os.path.dirname(os.path.abspath(__file__))
    BASE_DIR = os.path.dirname(_here) if os.path.basename(_here) == "src" else _here
except NameError:
    BASE_DIR = os.getcwd()
DATA_PATH = os.path.join(BASE_DIR, "data", "customer_360_ml_workshop.csv")
OUTPUT_DIR = os.path.join(BASE_DIR, "outputs")

ID_COL = "CustomerID"
CLASS_TARGET = "Churn"
REG_TARGET = "Future12MRevenueEGP"

NUMERIC_COLS = ["Age", "TenureMonths", "MonthlyUsageGB", "MonthlyChargeEGP",
                "NumServices", "SupportCalls6M", "LatePayments12M",
                "SatisfactionScore"]
CATEGORICAL_COLS = ["Region", "ContractType", "InternetType",
                    "PaperlessBilling", "AutoPay"]
SEGMENT_COLS = ["TenureMonths", "MonthlyUsageGB", "MonthlyChargeEGP",
                "NumServices", "SupportCalls6M", "LatePayments12M",
                "SatisfactionScore"]


def load_data():
    return pd.read_csv(DATA_PATH)


def save_fig(name):
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    path = os.path.join(OUTPUT_DIR, name)
    plt.tight_layout()
    plt.savefig(path, dpi=120)
    plt.close()
    print("Saved:", path)