# -*- coding: utf-8 -*-
"""Main .ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os
from common import load_data, OUTPUT_DIR
from part_a_eda import run_eda
from part_c_classification import run_classification
from part_d_regression import run_regression
from part_g_customer360 import run_customer360   # also runs Parts E and F


def banner(title):
    print("\n" + "=" * 70 + "\n" + title + "\n" + "=" * 70)


def main():
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    df = load_data()
    print("Dataset loaded:", df.shape)

    banner("PART A - EDA");                          run_eda(df)
    banner("PART B/C - PREPROCESSING + CLASSIFICATION"); run_classification(df)
    banner("PART D - REGRESSION");                   run_regression(df)
    banner("PART E/F/G - CLUSTERING, PCA, ANOMALIES, CUSTOMER 360"); run_customer360(df)
    print("\nAll done. Check the outputs/ folder.")


if __name__ == "__main__":
    main()