# -*- coding: utf-8 -*-
"""Part b preprocessing.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

from sklearn.compose import ColumnTransformer
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline
from sklearn.preprocessing import OneHotEncoder, StandardScaler
from common import load_data, NUMERIC_COLS, CATEGORICAL_COLS, ID_COL


def build_preprocessor():
    numeric = Pipeline([
        ("imputer", SimpleImputer(strategy="median")),
        ("scaler", StandardScaler()),
    ])
    categorical = Pipeline([
        ("imputer", SimpleImputer(strategy="most_frequent")),
        ("onehot", OneHotEncoder(handle_unknown="ignore")),
    ])
    return ColumnTransformer(
        [("num", numeric, NUMERIC_COLS), ("cat", categorical, CATEGORICAL_COLS)],
        sparse_threshold=0,
    )


def get_feature_names(fitted_preprocessor):
    ohe = fitted_preprocessor.named_transformers_["cat"].named_steps["onehot"]
    try:
        cat_names = list(ohe.get_feature_names_out(CATEGORICAL_COLS))
    except AttributeError:
        cat_names = list(ohe.get_feature_names(CATEGORICAL_COLS))
    return NUMERIC_COLS + cat_names


def get_features(df):
    return df[NUMERIC_COLS + CATEGORICAL_COLS].copy()


if __name__ == "__main__":
    df = load_data()
    X = get_features(df)
    print("Excluded columns:", [ID_COL, "Churn", "Future12MRevenueEGP"])
    print("Feature matrix:", X.shape)
    pre = build_preprocessor().fit(X)
    Xt = pre.transform(X)
    print("After preprocessing:", Xt.shape, "| NaNs left:", int(__import__("numpy").isnan(Xt).sum()))
    print("Feature names:", get_feature_names(pre))