# -*- coding: utf-8 -*-
"""part_f_pca_anomalies.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.decomposition import PCA
from sklearn.ensemble import IsolationForest
from common import (load_data, save_fig, RANDOM_STATE, SEGMENT_COLS, ID_COL, OUTPUT_DIR)
from part_e_clustering import run_clustering

CONTAMINATION = 0.03


def run_pca(Xs, seg_labels, seg_names):
    pca = PCA(n_components=2, random_state=RANDOM_STATE)
    Z = pca.fit_transform(Xs)
    ev = pca.explained_variance_ratio_
    print("Explained variance: PC1 = %.1f%%, PC2 = %.1f%%, total = %.1f%%"
              % (ev[0] * 100, ev[1] * 100, ev.sum() * 100))
    loadings = pd.DataFrame(pca.components_.T, index=SEGMENT_COLS, columns=["PC1", "PC2"])
    print("\nPCA loadings (what each component means):\n", loadings.round(2))

    for c in sorted(set(seg_labels)):
        m = seg_labels == c
        plt.scatter(Z[m, 0], Z[m, 1], alpha=0.5, s=14, label=seg_names[c])
    plt.xlabel("PC1 (%.0f%%)" % (ev[0] * 100)); plt.ylabel("PC2 (%.0f%%)" % (ev[1] * 100))
    plt.title("K-Means Segments in PCA Space"); plt.legend(fontsize=8)
    save_fig("pca_segments.png")
    return Z


def run_anomalies(df, Xs, Z):
    iso = IsolationForest(n_estimators=300, contamination=CONTAMINATION, random_state=RANDOM_STATE)
    flag = iso.fit_predict(Xs) == -1
    score = -iso.score_samples(Xs)
    print("\nAnomalies flagged: %d (%.1f%%)" % (flag.sum(), flag.mean() * 100))

    zdf = pd.DataFrame(Xs, columns=SEGMENT_COLS)
    top = np.argsort(-score)[:15]
    rows = []
    for i in top:
        feat = zdf.iloc[i].abs().idxmax()
        rows.append({ID_COL: df.loc[i, ID_COL], "AnomalyScore": round(score[i], 3),
                     "MostExtremeFeature": feat,
                     "Value": df.loc[i, feat], "StdDevsFromMean": round(zdf.iloc[i][feat], 2),
                     "Churn": df.loc[i, "Churn"]})
    top_df = pd.DataFrame(rows)
    print("\nTop 15 anomalies:\n", top_df.to_string(index=False))
    top_df.to_csv(os.path.join(OUTPUT_DIR, "top_anomalies.csv"), index=False)

    print("\nChurn rate: anomalies %.1f%% vs normal %.1f%%" % (
        (df.loc[flag, "Churn"] == "Yes").mean() * 100, (df.loc[~flag, "Churn"] == "Yes").mean() * 100))
    plt.scatter(Z[~flag, 0], Z[~flag, 1], s=10, alpha=0.3, label="Normal")
    plt.scatter(Z[flag, 0], Z[flag, 1], s=22, color="red", label="Anomaly")
    plt.xlabel("PC1"); plt.ylabel("PC2"); plt.title("Isolation Forest anomalies"); plt.legend()
    save_fig("anomalies_pca.png")
    print("\nNote: 'anomaly' means statistically unusual behaviour, NOT fraud. "
          "Each case needs business review (e.g. heavy legitimate users, billing errors).")
    return flag, score


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    df = load_data()
    Xs, labels, names = run_clustering(df)
    Z = run_pca(Xs, labels, names)
    run_anomalies(df, Xs, Z)