# -*- coding: utf-8 -*-
"""Part g customer360.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

# Commented out IPython magic to ensure Python compatibility.
import os
import numpy as np
import pandas as pd
from sklearn.pipeline import Pipeline
from sklearn.model_selection import StratifiedKFold, KFold, cross_val_predict
from sklearn.ensemble import RandomForestClassifier, GradientBoostingRegressor
from common import (load_data, RANDOM_STATE, CLASS_TARGET, REG_TARGET, ID_COL, OUTPUT_DIR)
from part_b_preprocessing import build_preprocessor, get_features
from part_e_clustering import run_clustering
from part_f_pca_anomalies import run_pca, run_anomalies

CHURN_THRESHOLD = 0.25
REVENUE_QUANTILE = 0.50


def out_of_fold_predictions(df):
    X = get_features(df)
    y = (df[CLASS_TARGET] == "Yes").astype(int)
    clf = Pipeline([("prep", build_preprocessor()),
                    ("model", RandomForestClassifier(
                        n_estimators=500, max_depth=8, min_samples_leaf=20,
                        max_features="sqrt", random_state=RANDOM_STATE, n_jobs=-1))])
    churn_prob = cross_val_predict(
        clf, X, y, cv=StratifiedKFold(5, shuffle=True, random_state=RANDOM_STATE),
        method="predict_proba")[:, 1]

    reg = Pipeline([("prep", build_preprocessor()),
                    ("model", GradientBoostingRegressor(random_state=RANDOM_STATE))])
    revenue = cross_val_predict(
        reg, X, df[REG_TARGET], cv=KFold(5, shuffle=True, random_state=RANDOM_STATE))
    return churn_prob, revenue


def run_customer360(df):
    churn_prob, revenue = out_of_fold_predictions(df)

    Xs, seg_labels, seg_names = run_clustering(df)
    Z = run_pca(Xs, seg_labels, seg_names)
    anomaly, _ = run_anomalies(df, Xs, Z)

    final = pd.DataFrame({
        ID_COL: df[ID_COL],
        "ChurnProbability": churn_prob.round(4),
        "PredictedRevenue12M_EGP": revenue.round(2),
        "Segment": [seg_names[c] for c in seg_labels],
        "AnomalyFlag": anomaly.astype(int),
    })
    rev_cut = final["PredictedRevenue12M_EGP"].quantile(REVENUE_QUANTILE)
    final["RetentionPriority"] = ((final["ChurnProbability"] >= CHURN_THRESHOLD) &
                                  (final["PredictedRevenue12M_EGP"] >= rev_cut)).astype(int)

    print("\n=== Retention-priority rule ===")
    print("Priority = churn probability >= %.2f AND predicted revenue >= median (%.0f EGP)"
            % (CHURN_THRESHOLD, rev_cut))
    print("Why: contact customers who are likely to leave AND worth keeping, "
          "so the retention budget goes where expected loss is highest.")
    n = final["RetentionPriority"].sum()
    print("Priority customers: %d (%.1f%%)" % (n, 100 * n / len(final)))
    p = final[final.RetentionPriority == 1]
    actual = (df.loc[p.index, CLASS_TARGET] == "Yes").mean()
    print("Actual churn rate inside priority group: %.1f%% (overall %.1f%%)"
            % (actual * 100, (df[CLASS_TARGET] == "Yes").mean() * 100))
    print("Predicted revenue at stake: %.0f EGP" % p["PredictedRevenue12M_EGP"].sum())
    print("\nPriority customers by segment:\n", p["Segment"].value_counts().to_string())

    path = os.path.join(OUTPUT_DIR, "customer_360_predictions.csv")
    final.to_csv(path, index=False)
    print("\nSaved:", path, final.shape)
    print(final.head())
    return final


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    run_customer360(load_data())