# -*- coding: utf-8 -*-
"""Part d regression.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LinearRegression, Ridge, Lasso
from sklearn.neighbors import KNeighborsRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.ensemble import RandomForestRegressor, GradientBoostingRegressor
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score
from common import load_data, save_fig, RANDOM_STATE, REG_TARGET, OUTPUT_DIR
from part_b_preprocessing import build_preprocessor, get_features


def get_models():
    rs = RANDOM_STATE
    return {
        "Linear Regression": LinearRegression(),
        "Ridge": Ridge(alpha=1.0, random_state=rs),
        "Lasso": Lasso(alpha=1.0, random_state=rs),
        "KNN Regressor": KNeighborsRegressor(n_neighbors=15),
        "Decision Tree": DecisionTreeRegressor(max_depth=5, random_state=rs),
        "Random Forest": RandomForestRegressor(n_estimators=200, min_samples_leaf=5, random_state=rs, n_jobs=-1),
        "Gradient Boosting": GradientBoostingRegressor(random_state=rs),
    }


def run_regression(df):
    X = get_features(df)
    y = df[REG_TARGET]
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=RANDOM_STATE)

    rows, preds = [], {}
    for name, model in get_models().items():
        pipe = Pipeline([("prep", build_preprocessor()), ("model", model)])
        pipe.fit(X_train, y_train)
        p = pipe.predict(X_test)
        preds[name] = p
        rows.append({"Model": name,
                     "MAE": mean_absolute_error(y_test, p),
                     "RMSE": np.sqrt(mean_squared_error(y_test, p)),
                     "R2": r2_score(y_test, p)})
    table = pd.DataFrame(rows).set_index("Model").round(3).sort_values("RMSE")
    print("Regression comparison:\n", table)
    table.to_csv(os.path.join(OUTPUT_DIR, "regression_comparison.csv"))

    best = table.index[0]
    print("\nBest model by RMSE:", best)
    plt.scatter(y_test, preds[best], alpha=0.35)
    lims = [y_test.min(), y_test.max()]
    plt.plot(lims, lims, "--")
    plt.xlabel("Actual"); plt.ylabel("Predicted")
    plt.title("Actual vs Predicted - " + best)
    save_fig("regression_actual_vs_predicted.png")
    return table


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    run_regression(load_data())