# -*- coding: utf-8 -*-
"""Part c classification.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split, GridSearchCV
from sklearn.pipeline import Pipeline
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier
from sklearn.svm import SVC
from sklearn.naive_bayes import GaussianNB
from sklearn.metrics import (accuracy_score, precision_score, recall_score,
                             f1_score, roc_auc_score, confusion_matrix,
                             ConfusionMatrixDisplay, roc_curve)
from common import (load_data, save_fig, RANDOM_STATE, CLASS_TARGET, OUTPUT_DIR)
from part_b_preprocessing import build_preprocessor, get_features, get_feature_names


def get_models():
    rs = RANDOM_STATE
    return {
        "Logistic Regression": LogisticRegression(max_iter=1000, random_state=rs),
        "KNN": KNeighborsClassifier(n_neighbors=15),
        "Decision Tree": DecisionTreeClassifier(max_depth=5, random_state=rs),
        "Random Forest": RandomForestClassifier(n_estimators=200, random_state=rs),
        "SVM": SVC(probability=True, random_state=rs),
        "Naive Bayes": GaussianNB(),
        "Gradient Boosting": GradientBoostingClassifier(random_state=rs),
    }


def metrics(y_true, y_pred, y_prob):
    return {"Accuracy": accuracy_score(y_true, y_pred),
            "Precision": precision_score(y_true, y_pred, zero_division=0),
            "Recall": recall_score(y_true, y_pred),
            "F1": f1_score(y_true, y_pred),
            "ROC-AUC": roc_auc_score(y_true, y_prob)}


def make_pipe(model):
    return Pipeline([("prep", build_preprocessor()), ("model", model)])


def plot_all_confusion_matrices(all_probs, y_test, threshold=0.5):
    fig, axes = plt.subplots(2, 4, figsize=(18, 8))
    for ax, (name, prob) in zip(axes.ravel(), all_probs.items()):
        pred = (prob >= threshold).astype(int)
        ConfusionMatrixDisplay(confusion_matrix(y_test, pred)).plot(ax=ax, colorbar=False)
        ax.set_title(name)
    save_fig("classification_confusion_matrices_all.png")


def plot_all_roc_curves(all_probs, y_test):
    plt.figure(figsize=(8, 6))
    for name, prob in all_probs.items():
        fpr, tpr, _ = roc_curve(y_test, prob)
        plt.plot(fpr, tpr, label="%s (AUC = %.2f)" % (name, roc_auc_score(y_test, prob)))
    plt.plot([0, 1], [0, 1], "--", color="gray")
    plt.xlabel("False Positive Rate"); plt.ylabel("True Positive Rate")
    plt.title("ROC curves - all models"); plt.legend(fontsize=8)
    save_fig("classification_roc_all.png")


def run_classification(df):
    X = get_features(df)
    y = (df[CLASS_TARGET] == "Yes").astype(int)
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, stratify=y, random_state=RANDOM_STATE)
    print("Train:", X_train.shape, "Test:", X_test.shape,
          "| churn rate train/test: %.3f / %.3f" % (y_train.mean(), y_test.mean()))

    rows = []
    all_probs = {}
    for name, model in get_models().items():
        pipe = make_pipe(model).fit(X_train, y_train)
        prob = pipe.predict_proba(X_test)[:, 1]
        all_probs[name] = prob
        rows.append(dict(Model=name, **metrics(y_test, (prob >= 0.5).astype(int), prob)))
    table = pd.DataFrame(rows).set_index("Model").round(3).sort_values("ROC-AUC", ascending=False)
    print("\nClassification comparison:\n", table)
    table.to_csv(os.path.join(OUTPUT_DIR, "classification_comparison.csv"))

    grid = GridSearchCV(
        make_pipe(RandomForestClassifier(random_state=RANDOM_STATE)),
        param_grid={"model__n_estimators": [300, 500],
                    "model__max_depth": [4, 6, 8, 12],
                    "model__min_samples_leaf": [5, 10, 20],
                    "model__max_features": ["sqrt", 0.5]},
        scoring="roc_auc", cv=5, n_jobs=-1)
    grid.fit(X_train, y_train)
    print("\nBest params:", grid.best_params_)
    print("Best CV ROC-AUC: %.3f" % grid.best_score_)
    best = grid.best_estimator_
    prob = best.predict_proba(X_test)[:, 1]
    print("Tuned RF on test:", {k: round(v, 3) for k, v in metrics(y_test, (prob >= 0.5).astype(int), prob).items()})

    all_probs["Tuned Random Forest"] = prob
    plot_all_confusion_matrices(all_probs, y_test)
    plot_all_roc_curves(all_probs, y_test)

    print("\nThreshold analysis:")
    thr_rows = []
    for t in [0.20, 0.25, 0.35, 0.50, 0.70]:
        pred = (prob >= t).astype(int)
        thr_rows.append({"Threshold": t,
                         "Precision": precision_score(y_test, pred, zero_division=0),
                         "Recall": recall_score(y_test, pred),
                         "F1": f1_score(y_test, pred),
                         "Flagged customers": int(pred.sum())})
    print(pd.DataFrame(thr_rows).round(3).to_string(index=False))

    names = get_feature_names(best.named_steps["prep"])
    imp = pd.Series(best.named_steps["model"].feature_importances_, index=names)
    imp = imp.sort_values(ascending=False)
    print("\nTop 10 churn predictors:\n", imp.head(10).round(3))
    imp.head(10)[::-1].plot(kind="barh", title="Random Forest feature importance (top 10)")
    save_fig("classification_feature_importance.png")
    return best


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    run_classification(load_data())