# -*- coding: utf-8 -*-
"""Part e clustering.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1S2O0Z4pDLHmGnVlBdUCSmlmTk3ozy0Eu
"""

import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.cluster import KMeans, AgglomerativeClustering, DBSCAN
from sklearn.metrics import silhouette_score, adjusted_rand_score
from sklearn.neighbors import NearestNeighbors
from common import load_data, save_fig, RANDOM_STATE, SEGMENT_COLS, OUTPUT_DIR

K_RANGE = range(2, 9)


def get_scaled_segment_data(df):
    X = SimpleImputer(strategy="median").fit_transform(df[SEGMENT_COLS])
    return StandardScaler().fit_transform(X)


def select_k(Xs):
    rows = []
    for k in K_RANGE:
        km = KMeans(n_clusters=k, n_init=10, random_state=RANDOM_STATE).fit(Xs)
        rows.append({"k": k, "inertia": km.inertia_,
                     "silhouette": silhouette_score(Xs, km.labels_)})
    res = pd.DataFrame(rows).set_index("k")
    print("K-Means selection:\n", res.round(3))
    fig, ax = plt.subplots(1, 2, figsize=(10, 4))
    ax[0].plot(res.index, res["inertia"], marker="o"); ax[0].set_title("Elbow (inertia)")
    ax[1].plot(res.index, res["silhouette"], marker="o"); ax[1].set_title("Silhouette score")
    for a in ax:
        a.set_xlabel("k")
    save_fig("kmeans_selection.png")
    res.round(4).to_csv(os.path.join(OUTPUT_DIR, "kmeans_selection.csv"))
    return res


def name_clusters(profile, overall_mean, overall_std):
    z = (profile - overall_mean) / overall_std
    names = {}
    for c in profile.index:
        r = z.loc[c]
        parts = []
        if r["TenureMonths"] > 0.3: parts.append("Loyal")
        elif r["TenureMonths"] < -0.3: parts.append("New")
        if r["MonthlyChargeEGP"] > 0.3: parts.append("High-Value")
        elif r["MonthlyChargeEGP"] < -0.3: parts.append("Low-Spend")
        if r["SupportCalls6M"] > 0.3 or r["LatePayments12M"] > 0.3 or r["SatisfactionScore"] < -0.3:
            parts.append("At-Risk")
        names[c] = " ".join(parts) if parts else "Core Mainstream"
    seen = {}
    for c, n in names.items():
        seen[n] = seen.get(n, 0) + 1
        if seen[n] > 1:
            names[c] = "%s #%d" % (n, seen[n])
    return names


def run_clustering(df, k=4):
    Xs = get_scaled_segment_data(df)
    select_k(Xs)
    print("\nSelected k = %d" % k)

    km = KMeans(n_clusters=k, n_init=10, random_state=RANDOM_STATE).fit(Xs)
    labels_km = km.labels_

    prof = df[SEGMENT_COLS].copy()
    prof["Segment"] = labels_km
    prof["ChurnRate"] = (df["Churn"] == "Yes").astype(int)
    prof["Revenue"] = df["Future12MRevenueEGP"]
    profile = prof.groupby("Segment").mean()
    profile.insert(0, "Size", prof.groupby("Segment").size())
    names = name_clusters(profile[SEGMENT_COLS], df[SEGMENT_COLS].mean(),
                          df[SEGMENT_COLS].std(ddof=0))
    profile.insert(1, "Name", pd.Series(names))
    print("\nCluster profiles:\n", profile.round(2).to_string())
    profile.round(3).to_csv(os.path.join(OUTPUT_DIR, "cluster_profiles.csv"))

    labels_ag = AgglomerativeClustering(n_clusters=k, linkage="ward").fit_predict(Xs)

    min_samples = 2 * Xs.shape[1]
    dist = np.sort(NearestNeighbors(n_neighbors=min_samples).fit(Xs).kneighbors(Xs)[0][:, -1])
    eps = float(np.percentile(dist, 90))
    plt.plot(dist); plt.axhline(eps, ls="--", color="red")
    plt.title("DBSCAN k-distance plot (eps = %.2f)" % eps)
    plt.xlabel("Points sorted"); plt.ylabel("Distance to %d-th neighbour" % min_samples)
    save_fig("dbscan_kdistance.png")
    labels_db = DBSCAN(eps=eps, min_samples=min_samples).fit_predict(Xs)

    def sil(l):
        m = l != -1
        return silhouette_score(Xs[m], l[m]) if len(set(l[m])) > 1 else float("nan")

    comp = pd.DataFrame({
        "K-Means": [len(set(labels_km)), silhouette_score(Xs, labels_km), 0],
        "Agglomerative": [len(set(labels_ag)), silhouette_score(Xs, labels_ag), 0],
        "DBSCAN": [len(set(labels_db)) - (1 if -1 in labels_db else 0), sil(labels_db),
                   int((labels_db == -1).sum())],
    }, index=["Clusters", "Silhouette", "Noise points (-1)"]).T
    print("\nAlgorithm comparison:\n", comp.round(3))
    print("Agreement K-Means vs Agglomerative (ARI): %.3f" % adjusted_rand_score(labels_km, labels_ag))
    print("DBSCAN label -1 = noise: points not dense enough to join any cluster "
          "(unusual customers), NOT a real segment.")
    comp.round(3).to_csv(os.path.join(OUTPUT_DIR, "clustering_comparison.csv"))
    return Xs, labels_km, names


if __name__ == "__main__":
    os.makedirs(OUTPUT_DIR, exist_ok=True)
    run_clustering(load_data())